name: Sedri
version: '${version}'
main: me.sedri.sedri.SedriPlugin
api-version: 1.18
depend:
  - LuckPerms
  - Vault
softdepend:
  - EcoEnchants
  - WorldGuard
  - WorldGuardExtraFlags
commands:
  keepgamemode:
    description: "Keeps your gamemode from the last world"
  tpbow:
    description: "Store data in a item"
  tpstick:
    description: "stick that tps you"
    permission: "sedri.tpstick"
  swordofthestars:
    description: "Sword of the stars"
  maxhealpot:
    description: "gives you a potion that will heal you to max health"
  shortbow:
    description: "gives a shorbow"
  gui:
    description: "opens a gui"
  sedrireload:
    description: "reloads the files n shit"
  pvp:
    description: "Toggles pvp."
    permission: "sedri.togglepvp"
  test:
    description: no
  ssudo:
    description: you dont get to do this command L
  hyperion:
    description: hello i go boom
  rreforge:
    description: rreforge
  beamrod:
    description: BEAMMMM
  givenull:
    description: gives a null barrier
  fot:
    description: fot
  spiritsceptre:
    description: spirit sceptre
#  gay:
#    description: "e a sports"